service:
  name: AutoSlideGenerator
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: false   # Node modules configuration for packaging
    packager: 'yarn'   # Packager that will be used to package your external modules
    excludeFiles: lambda/**/*.spec.ts # Provide a glob for files to ignore

# コレが大事
#
# ref.: https://serverless.com/framework/docs/providers/aws/guide/packaging/#packaging-functions-separately
package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1

functions:
  auto-slide-generator-slide-generate:
    handler: lambda/slide-generate/index.handler
    memorySize: 256
    timeout: 900
    events:
      - http:
          method: post
          path: slide/generate
          cors: true
