service:
  name: AutoSlideGenerator
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  dotenv:
    path: ./.env
    include:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_BOT_ACCESS_TOKEN
      - TWITTER_BOT_ACCESS_TOKEN_SECRET
      - GOOGLE_API_KEY
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - FLICKR_APIKEY
      - FLICKR_SECRET

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1

functions:
  slide-generate:
    handler: lambda/slide-generate/index.handler
    memorySize: 256
    timeout: 900
    events:
      - http:
          method: post
          path: slide/generate
          cors: true

  google-oauth:
    handler: lambda/google-oauth/index.handler
    memorySize: 128
    timeout: 900
    events:
      - http:
          method: get
          path: google/oauth
