service:
  name: AutoSlideGenerator
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dotenv:
    path: ./.env
    include:
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - TWITTER_BOT_ACCESS_TOKEN
      - TWITTER_BOT_ACCESS_TOKEN_SECRET
      - GOOGLE_API_KEY
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - FLICKR_APIKEY
      - FLICKR_SECRET

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1

functions:
  auto-slide-generator-slide-generate:
    handler: lambda/slide-generate/index.handler
    memorySize: 256
    timeout: 900
    events:
      - http:
          method: post
          path: slide/generate
          cors: true
