service:
  name: AutoSlideGenerator
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1

functions:
  auto-slide-generator-slide-generate:
    handler: lambda/slide-generate/index.handler
    memorySize: 256
    timeout: 900
    events:
      - http:
          method: post
          path: slide/generate
          cors: true
