name: FrontendDeploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      working-directory: ./frontend
      run: |
        yarn install
    - name: Register .env
      working-directory: ./frontend
      env:
        REACT_APP_API_ROOT_URL: ${{ secrets.REACT_APP_API_ROOT_URL }}
        REACT_APP_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_OAUTH_CLIENT_ID }}
        REACT_APP_GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.REACT_APP_GOOGLE_OAUTH_CLIENT_SECRET }}
      run: |
        echo "REACT_APP_API_ROOT_URL=${REACT_APP_API_ROOT_URL}" >> ./.env.production
        echo "REACT_APP_GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}" >> ./.env.production
        echo "REACT_APP_GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}" >> ./.env.production
    - name: yarn build
      working-directory: ./frontend
      run: |
        yarn run build
    - name: Archive Build Artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: ./frontend/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: build
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: build
