name: Server Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: setup ubuntu
      run: sudo apt-get --quiet update --yes
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      working-directory: ./server
      run: yarn install
    - name: serverless build
      working-directory: ./server
      run: |
        ./node_modules/serverless/bin/serverless package --package ./build
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: server/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: build
    - name: yarn install
      working-directory: ./server
      run: yarn install
    - name: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        ./server/node_modules/serverless/bin/serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_ACCESS_KEY}
        ./server/node_modules/serverless/bin/serverless deploy --package ./build